import React from 'react'
import { Link } from 'gatsby'

import Layout from '../components/layout'
import SEO from '../components/seo'
import Image from '../components/image'

const BudgetPage = () => (
  <Layout>
    <SEO title="Budget-constrained online summarisation" keywords={['online', 'video', 'summarisation', 'control-chart', 'egocentric']} />
    <h1>Budget-constrained online video summarisation of egocentric video using control charts</h1>
    <div style={{paddingBottom: '25px', paddingTop: '25px'}}>
	    Despite the existence of a large number of approaches for generating summaries from egocentric video, online video summarisation has not been fully explored yet. We present an online video summarisation algorithm to generate keyframe summaries during video capture. Event boundaries are identiﬁed using control charts and a keyframe is subsequently selected for each event. The number of keyframes is restricted from above which requires a constant review and possible reduction of the cumulatively built summary. The new method was compared against a baseline and a state-of-the-art online video summarisation methods. The evaluation was done on an egocentric video database (Activity of Daily Living (ADL)). Semantic content of the frames in the video was used to evaluate matches with ground truth. The summaries generated by the proposed method outperform those generated by the two competitors.
    </div>
    <hr />
    <div style={{ position: 'relative', paddingBottom: '56.25%', paddingTop: '25px', height: '0' ,marginBottom: '25px'}}>
    <iframe style={{ position: 'absolute', top: '0', left: '0', width: '100%', height: '100%' }} width="560" height="315" src="https://www.youtube.com/embed/5VowGnGlQ0g?vq=hd720&modestbranding=1&controls=0&amp;" frameBorder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
    </div>
    <hr />
    <div style={{paddingBottom: '25px'}}>
	    <Image name="visualisation" fluid />
	    <p>
		    Example of keyframe summaries obtained by (a) the budget-constrained control chart method (BCC), (b) a submodular-convex optimisation method (SCX), and (c) assigning uniform-time events (UE), and their matched frames with the ground truth, for ADL dataset video #16. The total number of events in this video is 13, and the BCC method missed just one event, eating food/drink.
	    </p>
    </div>
    <hr />
    <div style={{paddingBottom: '25px'}}>
    <h3>Reference</h3>
    Yousefi P., Matthews C.E. and Kuncheva L.I., Budget-Constrained Online Video Summarisation of Egocentric Video Using Control Charts. Proceedings of The 13th International Symposium on Visual Computing (ISVC 2018), 2018, Las Vegas, USA. Lecture Notes in Computer Science, Springer, vol 11241, pp 640 - 649.
    </div>
    <hr />
    <div>
	    <h3>Links</h3>
	    <p>
	    <a style={{paddingLeft: '5px'}} href="https://link.springer.com/chapter/10.1007/978-3-030-03801-4_56">Paper</a>
    </p>
    <p>
	    Code:
	    <a style={{paddingLeft: '5px'}}>GitHub?</a>
    </p>
    <p>
	    Data:
	    <a style={{paddingLeft: '5px'}} href="https://www.csee.umbc.edu/~hpirsiav/papers/ADLdataset/">Activities of Daily Living</a>
    </p>

    </div>
    <hr />
    <div>
    <Link style={{paddingRight: '15px'}} to="/">Video summarisation</Link>
    <a href="http://pages.bangor.ac.uk/~mas00a/activities/Leverhulme/project_RPG_2015_188.html">Project home</a>
    </div>
  </Layout>
)

export default BudgetPage
